# Generated by Django 5.2.11 on 2026-03-03 08:34

import ledger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(blank=True, validators=[ledger.models.validate_bio_length]),
        ),
    ]
